### PR TITLE
revert vulkan.msm8998.so to 3be114a4d1893663ec25ba2472954f7ab6fe4432

### PR DESCRIPTION
**Pull request by Kethen**
vulkan.msm8998.so from [051ade8a02f95b313485a4488fc2d5c4da8a8283](https://github.com/TheMuppets/proprietary_vendor_essential/commit/051ade8a02f95b313485a4488fc2d5c4da8a8283) of the old repo is incompatible with the shader compiler

No idea where that vulkan.msm8998.so on 051ade8a02f95b313485a4488fc2d5c4da8a8283 came from, it probably needs it's full adreno stack imported to work, instead of just that lib

Fixes the following on lineage-20 by reverting vulkan.msm8998.so to [3be114a4d1893663ec25ba2472954f7ab6fe4432](https://github.com/TheMuppets/proprietary_vendor_essential/commit/3be114a4d1893663ec25ba2472954f7ab6fe4432):
```
11-24 12:46:50.609  8102  8124 I AdrenoVK: Shader compilation failed for shaderType: 0
11-24 12:46:50.609  8102  8124 I AdrenoVK: Info log: ERROR: 0:1: '' : Unknown char 
11-24 12:46:50.609  8102  8124 I AdrenoVK: INTERNAL ERROR: no main() function!
11-24 12:46:50.609  8102  8124 I AdrenoVK: ERROR: 1 compilation errors.  No code generated.
11-24 12:46:50.609  8102  8124 I AdrenoVK: 
11-24 12:46:50.609  8102  8124 I AdrenoVK: 
11-24 12:46:50.609  8102  8124 E PPSSPP  : [G3D] Failed creating graphics pipeline! VK_INCOMPLETE
11-24 12:46:50.609  8102  8124 E PPSSPP  : [G3D] vs: 
11-24 12:46:50.609  8102  8124 E PPSSPP  : [END VS]
11-24 12:46:50.609  8102  8124 E PPSSPP  : [G3D] fs: 
11-24 12:46:50.609  8102  8124 E PPSSPP  : [END FS]
11-24 12:46:50.609  8102  8124 E PPSSPP  : [G3D] ======== END OF PIPELINE ==========
11-24 12:46:50.610  8102  8125 I AdrenoVK: Shader compilation failed for shaderType: 0
11-24 12:46:50.610  8102  8125 I AdrenoVK: Info log: ERROR: 0:1: '' : Unknown char 
11-24 12:46:50.610  8102  8125 I AdrenoVK: INTERNAL ERROR: no main() function!
11-24 12:46:50.610  8102  8125 I AdrenoVK: ERROR: 1 compilation errors.  No code generated.
11-24 12:46:50.610  8102  8125 I AdrenoVK: 
11-24 12:46:50.610  8102  8125 I AdrenoVK: 
11-24 12:46:50.610  8102  8125 E PPSSPP  : [G3D] Failed creating graphics pipeline! VK_INCOMPLETE
11-24 12:46:50.610  8102  8125 E PPSSPP  : [G3D] vs: 
11-24 12:46:50.610  8102  8125 E PPSSPP  : [END VS]
11-24 12:46:50.610  8102  8125 E PPSSPP  : [G3D] fs: 
11-24 12:46:50.610  8102  8125 E PPSSPP  : [END FS]
11-24 12:46:50.610  8102  8125 E PPSSPP  : [G3D] ======== END OF PIPELINE ==========
```

### CODE REVIEW

**Comment by Kethen** [comment]
probably make sense to ping @Tomoms and @npjohnson , fixed https://xdaforums.com/t/official-lineageos-20-for-the-essential-phone.4514841/page-2#post-87837883 as well on my device

**Comment by Tomoms** [comment]
Hi @Kethen 
I apologise, this problem has been reported multiple times, but I always paid little attention to it and preferred to work on other issues that I thought were more important.
Let me look into it and find a proper solution.

**Comment by Kethen** [comment]
Updated original PR comment to better describe when the problematic vulkan.msm8998.so was imported, and the commit this PR reverts the lib to

**Comment by npjohnson** [comment]
better solution incoming.

**Pull request closed without merging**
